# Generated by Django 5.0.7 on 2025-09-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_reciperating_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
